---
- name: Configure Debian Environment
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure Windows Environment
  ansible.builtin.include_tasks: setup-Windows.yml
  when: ansible_os_family == 'Windows'
