---
- name: Download Tableplus
  ansible.windows.win_get_url:
    url: "{{ tableplus_url }}"
    dest: C:\tmp\TablePlusSetup.exe
    checksum: "{{ tableplus_hash }}"
    checksum_algorithm: sha256

- name: Install Tableplus
  ansible.windows.win_package:
    path: C:\tmp\TablePlusSetup.exe
    product_id: "TablePlus_is1"
    arguments:
      - /verysilent
    state: present
