---
- name: Download MV C++ 2019 Redistributable Package (x64)
  ansible.windows.win_get_url:
    url: "{{ mysql_visual_studio }}"
    dest: C:\tmp\{{ mysql_visual_studio_package }}
    checksum: "{{ mysql_visual_studio_hash }}"
    checksum_algorithm: sha256

- name: Install MV C++ 2019 Redistributable Package (x64)
  ansible.windows.win_package:
    path: C:\tmp\{{ mysql_visual_studio_package }}
    arguments:
      - /quiet
      - /norestart
    product_id: "{0F03096E-F81F-48D0-AEE0-9F8513CD883F}"

- name: Download MySQL Server Installer
  ansible.windows.win_get_url:
    url: "{{ mysql_url }}"
    dest: C:\tmp\{{ mysql_package }}
    checksum: "{{ mysql_hash }}"
    checksum_algorithm: sha256
    validate_certs: false

- name: Install MySQL Server
  ansible.windows.win_package:
    path: C:\tmp\{{ mysql_package }}
    arguments:
      - /quiet
      - /norestart
    product_id: "{86F74ABA-67A4-46D7-B535-9DD5E58827A9}"

- name: Copy MySQL configuration file
  ansible.windows.win_copy:
    src: files/my.cnf
    dest: C:\Program Files\MySQL\MySQL Server 8.0

- name: Ensure that MySQL on Windows Path
  ansible.windows.win_path:
    elements: C:\Program Files\MySQL\MySQL Server 8.0\bin
    scope: machine
    state: present

- name: Create MySQL Server Service
  ansible.windows.win_service:
    name: MySQL80
    path: C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqld.exe" --defaults-file="C:\ProgramData\MySQL\MySQL Server 8.0\my.ini" MySQL80
    description: MySQL Server 8 Service
    username: NT AUTHORITY\NetworkService
    start_mode: auto
    state: started
