---
- name: Deploy fishbowl initial settings
  hosts: fishbowl.windows
  gather_facts: true
  vars_files:
    - vars/windows.yml
    - vars/fishbowl.yml
    - vars/mysql.yml
    - vars/vscode.yml
  roles:
    - { role: settings, tags: settings }
    - { role: vscode, tags: vscode }
    - { role: mysql, tags: mysql }
    - { role: fishbowl, tags: fishbowl }
