---
- name: Provision fishbowl server
  hosts: fishbowl.ubuntu
  gather_facts: true
  vars_files:
    - vars/ubuntu.yml
    - vars/fishbowl.yml
  roles:
    - { role: common, tags: common }
    - { role: java, tags: java }
    - { role: mysql, tags: mysql }
    - { role: fishbowl, tags: fishbowl } # TODO: need auto unattended answer file.
